version: '2'
services:
 app:
  build: .
  ports:
  - "32600:80"
  links:
  - db:mysql
 db:
  image: mariadb
  environment:
   MYSQL_ROOT_PASSWORD: somepassword
   MYSQL_DATABASE: tastydb
   MYSQL_USER: tastyuser
   MYSQL_PASSWORD: tastypass
